/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:08f3180b-7592-4aae-b0f8-f63941ae7c12",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_3aER48oir",
    "aws_user_pools_web_client_id": "37uq22r8i7bfdbhs4r53hcr6af",
    "oauth": {}
};


export default awsmobile;
